run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - gosec
    - gocritic
    - ineffassign
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
  gosec:
    excludes:
      - G104 # duplex of errcheck
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
